name: Laravel

on:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
